import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, it } from 'vitest'
import { NameGenerator } from '../src/components/NameGenerator'
import { readNameWorkspace, writeNameWorkspace, parseAiNames } from '../src/lib/name-workspace'
beforeEach(() => localStorage.clear())
afterEach(cleanup)
it('locks results, browses and removes favorites, restores historical names', () => {
  render(<NameGenerator />)
  fireEvent.click(screen.getByRole('button', { name: /名字生成器/ }))
  fireEvent.click(screen.getByRole('button', { name: '生成' }))
  const name = screen.getAllByRole('button', { name: /^锁定/ })[0].getAttribute('aria-label')!.slice(2)
  fireEvent.click(screen.getByRole('button', { name: '锁定' + name }))
  fireEvent.click(screen.getByRole('button', { name: '收藏' + name }))
  fireEvent.click(screen.getByRole('button', { name: '重新生成' }))
  expect(screen.getByRole('button', { name: '解锁' + name })).toBeTruthy()
  fireEvent.click(screen.getByRole('tab', { name: '收藏夹' }))
  expect(screen.getByRole('button', { name: '复制' + name })).toBeTruthy()
  fireEvent.change(screen.getByRole('textbox', { name: '搜索收藏' }), { target: { value: '不存在的词' } })
  expect(screen.queryByRole('button', { name: '复制' + name })).toBeNull()
  fireEvent.change(screen.getByRole('textbox', { name: '搜索收藏' }), { target: { value: '' } })
  fireEvent.click(screen.getByRole('button', { name: '取消收藏' + name }))
  expect(screen.getByText('尚未收藏名字。')).toBeTruthy()
  fireEvent.click(screen.getByRole('tab', { name: '最近生成' }))
  fireEvent.click(screen.getAllByRole('button', { name: '恢复结果' })[1])
  expect(screen.getByRole('button', { name: '复制' + name })).toBeTruthy()
})
it('saves and restores project presets and vocabulary', () => {
  render(<NameGenerator />)
  fireEvent.click(screen.getByRole('button', { name: /名字生成器/ }))
  fireEvent.change(screen.getByLabelText('指定姓氏'), { target: { value: '欧阳' } })
  fireEvent.click(screen.getByRole('tab', { name: '词库与预设' }))
  fireEvent.blur(screen.getByLabelText('专属词根'), { target: { value: '清,云,月' } })
  fireEvent.change(screen.getByLabelText('预设名称'), { target: { value: '欧阳家族' } })
  fireEvent.click(screen.getByRole('button', { name: '保存当前条件' }))
  const saved = readNameWorkspace('')
  expect(saved.roots).toEqual(['清', '云', '月'])
  expect(saved.presets[0].rules.surname).toBe('欧阳')
  fireEvent.click(screen.getByRole('button', { name: '应用' }))
  expect((screen.getByLabelText('指定姓氏') as HTMLInputElement).value).toBe('欧阳')
  expect(readNameWorkspace('another-project').presets).toEqual([])
  writeNameWorkspace('another-project', saved)
  expect(readNameWorkspace('another-project')).toEqual(saved)
})
it('recovers malformed storage and validates structured AI results', () => {
  localStorage.setItem('novelforge:name-workspace:v1:x', '{')
  expect(readNameWorkspace('x').history).toEqual([])
  expect(parseAiNames('```json\n[{"name":"月港","explanation":"月光下的港口"},{"name":"月港"}]\n```', 'location', '中文古风')).toHaveLength(1)
  expect(() => parseAiNames('not json', 'character', '中文现代')).toThrow()
})
